[package]
name = "rl-inventory-prices"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
rayon = "1.7.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
scraper = "0.16.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
